services:
  - type: web
    name: survey-converter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: web_app.py
    disk:
      name: survey-data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1